# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0af69130fc82cb0b9bada35b2afde197159ab9d55b52b541d7126464fd112d845c047dd1c4423d6979ddcf7a6551931e042c3df1f0c6d1790f679a84286d7a7b

test:
  secret_key_base: 32ba97bbecd23b749c9645e1bdac64b27ea2d8d6a3041ddd0c1b0bca39c15198e1ba5cc4a8b8ccd7033bef9b93c56f71932ec7be6dd378fa0dc922098deb12dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
